const json = {
    ref: "refs/heads/main",
    before: "5c996d56322762affbc8af9426546985feee3b52",
    after: "ddcecfa0fa43480104e311e7f66ae4244274dd56",
    repository: {
        id: 606394036,
        node_id: "R_kgDOJCTWtA",
        name: "DiscordPushBot",
        full_name: "ion22666/DiscordPushBot",
        private: false,
        owner: {
            name: "ion22666",
            email: "50714035+ion22666@users.noreply.github.com",
            login: "ion22666",
            id: 50714035,
            node_id: "MDQ6VXNlcjUwNzE0MDM1",
            avatar_url: "https://avatars.githubusercontent.com/u/50714035?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/ion22666",
            html_url: "https://github.com/ion22666",
            followers_url: "https://api.github.com/users/ion22666/followers",
            following_url: "https://api.github.com/users/ion22666/following{/other_user}",
            gists_url: "https://api.github.com/users/ion22666/gists{/gist_id}",
            starred_url: "https://api.github.com/users/ion22666/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/ion22666/subscriptions",
            organizations_url: "https://api.github.com/users/ion22666/orgs",
            repos_url: "https://api.github.com/users/ion22666/repos",
            events_url: "https://api.github.com/users/ion22666/events{/privacy}",
            received_events_url: "https://api.github.com/users/ion22666/received_events",
            type: "User",
            site_admin: false,
        },
        html_url: "https://github.com/ion22666/DiscordPushBot",
        description: null,
        fork: false,
        url: "https://github.com/ion22666/DiscordPushBot",
        forks_url: "https://api.github.com/repos/ion22666/DiscordPushBot/forks",
        keys_url: "https://api.github.com/repos/ion22666/DiscordPushBot/keys{/key_id}",
        collaborators_url: "https://api.github.com/repos/ion22666/DiscordPushBot/collaborators{/collaborator}",
        teams_url: "https://api.github.com/repos/ion22666/DiscordPushBot/teams",
        hooks_url: "https://api.github.com/repos/ion22666/DiscordPushBot/hooks",
        issue_events_url: "https://api.github.com/repos/ion22666/DiscordPushBot/issues/events{/number}",
        events_url: "https://api.github.com/repos/ion22666/DiscordPushBot/events",
        assignees_url: "https://api.github.com/repos/ion22666/DiscordPushBot/assignees{/user}",
        branches_url: "https://api.github.com/repos/ion22666/DiscordPushBot/branches{/branch}",
        tags_url: "https://api.github.com/repos/ion22666/DiscordPushBot/tags",
        blobs_url: "https://api.github.com/repos/ion22666/DiscordPushBot/git/blobs{/sha}",
        git_tags_url: "https://api.github.com/repos/ion22666/DiscordPushBot/git/tags{/sha}",
        git_refs_url: "https://api.github.com/repos/ion22666/DiscordPushBot/git/refs{/sha}",
        trees_url: "https://api.github.com/repos/ion22666/DiscordPushBot/git/trees{/sha}",
        statuses_url: "https://api.github.com/repos/ion22666/DiscordPushBot/statuses/{sha}",
        languages_url: "https://api.github.com/repos/ion22666/DiscordPushBot/languages",
        stargazers_url: "https://api.github.com/repos/ion22666/DiscordPushBot/stargazers",
        contributors_url: "https://api.github.com/repos/ion22666/DiscordPushBot/contributors",
        subscribers_url: "https://api.github.com/repos/ion22666/DiscordPushBot/subscribers",
        subscription_url: "https://api.github.com/repos/ion22666/DiscordPushBot/subscription",
        commits_url: "https://api.github.com/repos/ion22666/DiscordPushBot/commits{/sha}",
        git_commits_url: "https://api.github.com/repos/ion22666/DiscordPushBot/git/commits{/sha}",
        comments_url: "https://api.github.com/repos/ion22666/DiscordPushBot/comments{/number}",
        issue_comment_url: "https://api.github.com/repos/ion22666/DiscordPushBot/issues/comments{/number}",
        contents_url: "https://api.github.com/repos/ion22666/DiscordPushBot/contents/{+path}",
        compare_url: "https://api.github.com/repos/ion22666/DiscordPushBot/compare/{base}...{head}",
        merges_url: "https://api.github.com/repos/ion22666/DiscordPushBot/merges",
        archive_url: "https://api.github.com/repos/ion22666/DiscordPushBot/{archive_format}{/ref}",
        downloads_url: "https://api.github.com/repos/ion22666/DiscordPushBot/downloads",
        issues_url: "https://api.github.com/repos/ion22666/DiscordPushBot/issues{/number}",
        pulls_url: "https://api.github.com/repos/ion22666/DiscordPushBot/pulls{/number}",
        milestones_url: "https://api.github.com/repos/ion22666/DiscordPushBot/milestones{/number}",
        notifications_url: "https://api.github.com/repos/ion22666/DiscordPushBot/notifications{?since,all,participating}",
        labels_url: "https://api.github.com/repos/ion22666/DiscordPushBot/labels{/name}",
        releases_url: "https://api.github.com/repos/ion22666/DiscordPushBot/releases{/id}",
        deployments_url: "https://api.github.com/repos/ion22666/DiscordPushBot/deployments",
        created_at: 1677323072,
        updated_at: "2023-02-25T11:33:59Z",
        pushed_at: 1677326688,
        git_url: "git://github.com/ion22666/DiscordPushBot.git",
        ssh_url: "git@github.com:ion22666/DiscordPushBot.git",
        clone_url: "https://github.com/ion22666/DiscordPushBot.git",
        svn_url: "https://github.com/ion22666/DiscordPushBot",
        homepage: null,
        size: 13,
        stargazers_count: 0,
        watchers_count: 0,
        language: "JavaScript",
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: {
            key: "apache-2.0",
            name: "Apache License 2.0",
            spdx_id: "Apache-2.0",
            url: "https://api.github.com/licenses/apache-2.0",
            node_id: "MDc6TGljZW5zZTI=",
        },
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: "public",
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: "main",
        stargazers: 0,
        master_branch: "main",
    },
    pusher: {
        name: "ion22666",
        email: "50714035+ion22666@users.noreply.github.com",
    },
    sender: {
        login: "ion22666",
        id: 50714035,
        node_id: "MDQ6VXNlcjUwNzE0MDM1",
        avatar_url: "https://avatars.githubusercontent.com/u/50714035?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/ion22666",
        html_url: "https://github.com/ion22666",
        followers_url: "https://api.github.com/users/ion22666/followers",
        following_url: "https://api.github.com/users/ion22666/following{/other_user}",
        gists_url: "https://api.github.com/users/ion22666/gists{/gist_id}",
        starred_url: "https://api.github.com/users/ion22666/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/ion22666/subscriptions",
        organizations_url: "https://api.github.com/users/ion22666/orgs",
        repos_url: "https://api.github.com/users/ion22666/repos",
        events_url: "https://api.github.com/users/ion22666/events{/privacy}",
        received_events_url: "https://api.github.com/users/ion22666/received_events",
        type: "User",
        site_admin: false,
    },
    created: false,
    deleted: false,
    forced: false,
    base_ref: null,
    compare: "https://github.com/ion22666/DiscordPushBot/compare/5c996d563227...ddcecfa0fa43",
    commits: [
        {
            id: "ddcecfa0fa43480104e311e7f66ae4244274dd56",
            tree_id: "7f9ad2ca2ea5256b6bb3845992a9882e4d19ddbf",
            distinct: true,
            message: "Update README.md",
            timestamp: "2023-02-25T14:04:48+02:00",
            url: "https://github.com/ion22666/DiscordPushBot/commit/ddcecfa0fa43480104e311e7f66ae4244274dd56",
            author: {
                name: "giovanni",
                email: "50714035+ion22666@users.noreply.github.com",
                username: "ion22666",
            },
            committer: {
                name: "GitHub",
                email: "noreply@github.com",
                username: "web-flow",
            },
            added: [],
            removed: [],
            modified: ["README.md"],
        },
    ],
    head_commit: {
        id: "ddcecfa0fa43480104e311e7f66ae4244274dd56",
        tree_id: "7f9ad2ca2ea5256b6bb3845992a9882e4d19ddbf",
        distinct: true,
        message: "Update README.md",
        timestamp: "2023-02-25T14:04:48+02:00",
        url: "https://github.com/ion22666/DiscordPushBot/commit/ddcecfa0fa43480104e311e7f66ae4244274dd56",
        author: {
            name: "giovanni",
            email: "50714035+ion22666@users.noreply.github.com",
            username: "ion22666",
        },
        committer: {
            name: "GitHub",
            email: "noreply@github.com",
            username: "web-flow",
        },
        added: [],
        removed: [],
        modified: ["README.md"],
    },
};

module.exports = json;
